version: '3'
services:
  api:
    image: node:alpine
    volumes:
      - ./:/app
    ports:
      - "3000:8080"
    working_dir: /app
    command: npm start
    networks:
    - mynetwork

networks:
  mynetwork:
